DROP DATABASE IF EXISTS medipherd;
CREATE DATABASE medipherd;

DROP TABLE IF EXISTS keywords_relation;
DROP TABLE IF EXISTS materials_relation;
DROP TABLE IF EXISTS materials;
DROP TABLE IF EXISTS keywords;
DROP TABLE IF EXISTS plants;

CREATE TABLE plants(
	plant_id CHAR(4) NOT NULL,
    plant_name VARCHAR(30) NOT NULL,
    plant_othernames VARCHAR(120),
    plant_family VARCHAR(20),
    plant_genus VARCHAR(20),
    plant_species VARCHAR(20),
    plant_chemconst VARCHAR(1000),
    plant_usage VARCHAR(1000),
    plant_refs VARCHAR(1000),
    PRIMARY KEY (plant_id)
);
CREATE TABLE materials(
	mat_id CHAR(3) NOT NULL,
    mat_desc VARCHAR(20),
    PRIMARY KEY (mat_id)
);
CREATE TABLE keywords(
    keyw_id CHAR(4) NOT NULL,
    keyw_desc VARCHAR(30),
    PRIMARY KEY (keyw_id)
);
CREATE TABLE materials_relation(
    rid_mat int AUTO_INCREMENT,
    plant_id CHAR(4),
    mat_id CHAR(3),
    PRIMARY KEY (rid_mat),
    FOREIGN KEY (plant_id) REFERENCES plants(plant_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (mat_id) REFERENCES materials(mat_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE keywords_relation(
    rid_keyw int AUTO_INCREMENT,
    plant_id CHAR(4),
    keyw_id CHAR(4),
    PRIMARY KEY (rid_keyw),
    FOREIGN KEY (plant_id) REFERENCES plants(plant_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (keyw_id) REFERENCES keywords(keyw_id) ON DELETE CASCADE ON UPDATE CASCADE
);


INSERT INTO plants(plant_id, plant_name, plant_othernames, plant_family, plant_genus, plant_species, plant_usage, plant_chemconst, plant_refs) VALUES
("P001", "Tongkat Ali", "Pasak bumi (Indonesia)", "Simaroubaceae", "Eurycoma", "longifolia", "It is used as an antimalaria, antioxidant, and cytotoxic E. longifolia extract and its fractions exert a direct antiproliferative activity on human breast cencer cell line MCF-7. Also antibacterial, the alcoholic and acetone extracts from leaves and stem extracts were active on both Grampositive and Gram negative bacteria.", "quassinoids, squalene derivatives, biphenylneolignans, tirucallane type trtertpenes, canthine-6-one and β-carboline alkaloid.", "https://pubs.acs.org/doi/10.1021/np400701k-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/10803359/-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/15138004/-MEDIPHERD-https://www.ijpsnonline.com/index.php/ijpsn/article/view/596-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/16158965/-MEDIPHERD-http://smj.psmmc.med.sa/index.php/smj/article/viewFile/5971/3745-MEDIPHERD-http://www.hindawi.com/journals/ecam/2013/102987/-MEDIPHERD-http://www.globinmed.com/index.php?option=com_content&view=article&id=62689:eurycoma-longifolia&catid=369"),
("P002", "Terung Susu Kambing", "Nipple fruit, titty fruit", "Solanaceae", "Solanum", "mammosum", "The juice of the fruit shows some detergent activity and can be used for washing clothing.", "Solasodine", "http://agris.fao.org/agris-search/search/display.do?f=1981-MEDIPHERD-http://link.springer.com/chapter/10.1007/978-94-007-5628-1_42#page-1-MEDIPHERD-http://thenerdygardener.hubpages.com/hub/Udder-Fruit-Solanum-mammosum"),
("P003", "Temukunci", "Schlechtar, Kaempferia pandurata Roxb., Gastrochilus rotundus", "Zingiberaceae", "Boesenbergia", "rotunda", "BR rhizome ethanolic extract treatment improved liver histopathology, immunohistochemistry, biochemistry, triggered apoptosis, and inhibitied cytokines, extracellular matrix proteins and hepatocytes proliferation. B. rotunda extract has potential antibacterial activity against E. Coli.", "-", "http://www.hindawi.com/journals/ecam/2013/157456/-MEDIPHERD-https://ph02.tci-thaijo.org/index.php/SciTechAsia/article/download/182851/164603/-MEDIPHERD-https://www.researchgate.net/publication/259647614_Toxicological_and_clastogenic_evaluation_of_pinocembrin_and_pinostrobin_isolated_from_Boesenbergia_pandurata_in_Wistar_rats-MEDIPHERD-http://www.ncbi.nlm.nih.gov/pmc/-MEDIPHERD-http://www.ifrj.upm.edu.my/-MEDIPHERD-http://www.kew.org/plants-fungi/Boesenbergia-rotunda.htm"),
("P004", "Temulawak", "Javanese turmeric", "Zingiberaceae", "Curcuma", "xanthorrihiza", "The oil showed antibacterial activity. Hepaprotective, the extract could reduce significantly the acute elevation of serum transaminases levels induced by the two kinds of hepatotoxins, and alleviated the degree of liver damage at 24 hours after the intraperitoneal administration of two hepatotoxins. Methanol extract of the dried rhizomes showed analgesic and diuretic activity. It is also used as a cholesterol lowering agent, gives anti-inflammatory effect, is an anti fungal, and have antioxidant and immunostimulant activty", "Xanthorrhizol. Essential oil from the rhizome contents: the derivatives of xanthorihizol, camphene and curcumene, monoterpene hydrocarbons, oxygenated monoterpenes, susquiterpene, hydrocarbons and other minor compounds. Germacrone.Curcuminoids (1-(4-hydroxy-3,5-dimethoxyphenyl)-7(4-hydroxy-3-methoxyphenyl)-(1E,6E)1-,6-heptadiene-3,4-dione.", "https://www.scholarsresearchlibrary.com/articles/in-vivo-toxicological-investigations-of-standardized-ethanolic-extract-ofcurcuma-xanthorrhiza-roxb-rhizome.pdf-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/10763606/-MEDIPHERD-http://www.banglajol.info/index.php/-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/8571920/-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/17587672/-MEDIPHERD-https://www.sciencedirect.com/science/article/abs/pii/S2221169112602883-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/2379278/-MEDIPHERD-https://www.sciencedirect.com/science/article/abs/pii/003194229283748N-MEDIPHERD-https://www.researchgate.net/publication/230087749_Influence_of_curcuma_Curcuma_xanthorrhiza_Roxb_on_lipid_metabolism_in_rabbits-MEDIPHERD-http://jac.oxfordjournals.org/%20content/57/6/1231.full.pdf-MEDIPHERD-http://www.hanannaqq.com/2012/07/nature-herb-temulawak.html-MEDIPHERD-http://books.google.com.my/books.curcuma"),
("P005", "Tembaga Suasa", "Pokok bakung", "Amaryllidaecae", "Crinum", "asiaticum", "The leaf of Crinum asiaticum is a natural source of antibacterial compounds. The bulb extract showed significant zone of inhibition against all Gram-positive and Gram-negative bacteria. The anti‐inflammatory activity of the same extract was estimated volumetrically by measuring the mean increase in hind paw volume of carrageenan‐induced Wistar albino rat with the help of plethysmometer. Ethyl acetate and alkaline ethylacetate soluble fractions of the bulbs of Crinum asiaticum var. japonicum showed significant cytoxicity against Lewis lung carcinoma tumor cells.", "(+)-siculine, 1-epijosephinine , 7-methoxycrinamabine, 2-O-acetylcrinamabine, 3-O-acetyl-8-O-demethylmaritidine, 2-O-acetylbulbisine, and 1-O-acetylbulbisine. In addition, dihydrovittatine and 8-O-demethyloxomaritidine (Chen CK et al 2011)", "https://pubs.acs.org/doi/abs/10.1021/np100819n-MEDIPHERD-http://www.journalcra.com/article/evaluation-antibacterial-activity-and-phytochemical-analysis-crinum-asiaticum-MEDIPHERD-https://www.banglajol.info/index.php/BJM/article/view/11801-MEDIPHERD-https://www.jstage.jst.go.jp/article/cpb/49/9/49_9_1217/_article"),
("P006", "Susun Kelapa", "Pagiantha peninsularis var. brevituba, Ervatamia corymbosa, Pagiantha peninsularis, Flore Pleno, East Indian Rosebay, Flower of Love", "Apocynaceae", "Tabernaemontana", "corymbosa", "The crude alkaloid extracts were tested against four bacterial and two fungi species by using disc diffusion method. It is found that this plant act as microbial agent and inhibit the growth of Baciluus cereus, Pseudomonas aeruginosa, Staphylococcus, Candida albicans, Esscherichia coli. The zones of inhibiton against the tested bacteria were found in the range of 7.00 to 14.75 mm, along with their MIC and MBC/MFC values ranging from 0.37-1.11 mg/mL and 3.33-10.00 mg/mL. Bistabercarpamine A (1), alkaloid compound found in T.corymbosa exhibited moderate cell growth inhibitory activity against HepG-2 cells with IC50 of 38.14 ± 1.1 μM", "The most important group are the alkaloids. Bistabercarpamines A (1) and B (2), vobasinyl-chippiine-type bisindole alkaloid from the leaves of Tabernaemontana corymbosa. The structures were elucidated on the basis of spectroscopic data, and the absolute configurations of these isolates were determined by CD excition chirality method. Four tetracyclic oxindole alkaloids, 7(R)- and 7(S)-geissoschizol oxindole (1 and 2), 7(R),16(R)- and 7(S),16(R)–19(E)-isositsirikine oxindole (3 and 4), in addition to a taberpsychine derivative, N(4)-demethyltaberpsychine (5), were isolated and the structures were established using NMR and MS analysis (Kuan et al., 2009). Conodiparine ABD (vobasine type) and ervatamine also can be found in T. Corymbosa (Chua et al., 2001)", "http://irep.iium.edu.my/4439/-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/19643450/"),
("P007", "Sesudu", "Indian spurge tree (English), sesudu (Malay), Soro-soro (Tag)", "Euphorbiaceae", "Euphorbia", "neriifolia", "Leaf extract give significant diuretic effects. The crude leaves extracts were anti fungal property to Aspergillus spp, the Aspegillus and Aspergillus niger. The hepatoprotective effect of saponin fraction isolated from leaf on CCl4-induced hepatoxicity on rat. Hydro-alcoholic extract of dried leaves in treatment of inflammation and analgesic activity. It has been found out the effect of sub-acute administration of leaf extract on some haematoligical, biochemical, histological, biochemical, histological and antioxidant enzyme status of rat liver and kidney following 21 and 45 days treatment. The aqueous extract when applied topically facilated the healing of surgically produced cuteneous wounds in guinea pigs. It has increased the gain in tensile strength, DNA content and promoted epithelization.", "Triterpenes (nerrifolione), flavonoids and steroidal saponins, sugar tannins, flavonoids, alkaloids and triterpenoidal saponin", "https://www.researchgate.net/publication/228456016_EUPHORBIA_NERIIFOLIA_LINN_A_PHYTOPHARMACOLOGICAL_REVIEW/fulltext/0009d8b62346a78f7e579dd4/EUPHORBIA-NERIIFOLIA-LINN-A-PHYTOPHARMACOLOGICAL-REVIEW.pdf-MEDIPHERD-http://www.arjournals.org/index.php/ijpm/article/view/114-MEDIPHERD-https://www.semanticscholar.org/paper/PESTICIDAL-EFFECT-OF-EUPHORBIA%2C-NERIUM-AND-LATEX-ON-Singh-Shukla/7e2a1f2d505caf448eab0c717d87554a1a9f071a-MEDIPHERD-http://www.i-scholar.in/index.php/Rjppd/article/view/58486-MEDIPHERD-http://www.ncbi.nlm.nih.gov/pubmed/14766154-MEDIPHERD-http://region3.dost.gov.ph/index.php"),
("P008", "Setawar Halia Merah", "spiral ginger or Crepe gingeror Red Button Ginger", "Costaceae", "Costus", "speciosus", "The treatment of the STZ-induced diabetic with costunolide and isolated remanthin alleviated the oxidative stress conditions, indicating the antioxidant property. Fresh juice of the rhizomes increased the tone, amplitude and frequency of rhythmic contractions of isolated uterus of some animals and human. Antimicrobial property is shown in aqueous extract of rhizome which have antibacterial activity against Staphylococcus aureus. Rhizome has antihelmintic, astringent, expectorant properties. The rhizome extract is used as tonic and useful in relieving burning sensation, constipation, leprosy, asthma, bronchitis, anaemia and other skin ailments. Remedy for fever. Hepatoprotective. Rhizome paste is used for treating boils and also to make sexual hormones and contraceptives. Rhizome used for treating snake bites. Cardiotonic, hydrochloetic, diuretic and CNS despressant activity, antifertility, anticholineterase, anti-inflammatory, antipyretic and antihelminthic properties were also shown. Leaves are used for scabies and stomach ailments. Stems are ground into paste and applied for blisters.", "Rhizome: steroid sapogenin, diosgenin. (Sterol, Flavanoid, Steroid, Anthraquinones, essential oil, coumarin & carboxlic acid, cardiac glycosides, saponin, alkaloid) Rhizome: Tigogenin and diosgenin, curcumin and curcuminoids Tetradecyl 13-methylpentadecanoate, tetradecyl 11-methyltridecanoate, 14-oxotricosanoic acid, 14-oxoheptacosanoic acid & 15-oxooctacosanoic acid. Methyl 3-(4-hydroxyphenyl)-2E propenoate. Susquiterpene: Costunolide and eremanthin Seed : hypotensive and spasmolytic effect. Saponin. Seed oil: 6 % consists of palmitic acid (55.97%), oleic acid (23.75%), linoleic, stearic, myristic and lauric acids. Defatted seeds contained diosgenin, glucose, galactose amd rhamnose. Seed: quinonesdihydrophytylplastoquinone & 6-methyl derivatives and α- tocopherol. Roots: 31-norcycloartanone, cycloartanol, cycloartenol and cyclolaudenol . 5 α-stigmasten-3b-ol, sitosterol-B-D-glucoside, dioscin, prosapogenins A & B of dioscin, gracillin and quinines, saponin. Sterol - 5α-stigmast-9(11)-en-3β-ol Leaves: α-amyrinsterate, β-amyrin and lupeolPalmitates was isolated from leaves.", "http://www.hindawi.com/journals/chem/2010/605735/abs/-MEDIPHERD-http://www.ethnobotanyjournal.org/vol8/i1547-3465-08-061.pdf-MEDIPHERD-http://download.springer.com/static/pdf/813/art%253A10.1007%252FBF01898450.pdf?auth66=1381541810_6dbd24ffca1f4348959150caf50cdb4e&ext=.pdf-MEDIPHERD-http://www.researchgate.net/publication/-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/20709041/"),
("P009", "Serai Wangi", "Citronella", "Graminae", "Andropogon", "confertiflorus", "used as antimosquito agent, antifungal agent, and repellant", "Essential oils: citronellal, citronellol, limonene, geranial and feraniol. Citronellal was the main essential oil component in the matured plants (Chan L.K. et al 2005). Alpha-cubebene, camphene, geraniol, limonene, myrcene, palmitic acid and sabinen were the major compounds identified. The essential oil was investigated for its antioxidant (DPPH assay), anti-inflammatory (5-lipoxygenase assay), antimicrobial (disk diffusion) and anti-mosquito properties (insecticidal, larvicidal and repellency assays) (Naidoo N ,et al, 2008)", "https://pubmed.ncbi.nlm.nih.gov/15049444/-MEDIPHERD-https://link.springer.com/article/10.1007/BF03030574-MEDIPHERD-https://www.researchgate.net/publication/272506220_EVALUATION_OF_ANTIBACTERIAL_ACTIVITY_OF_SEVERAL_SOUTH_AFRICAN_TREES_AND_ISOLATION_OF_TWO_BIFLAVONOIDS_WITH_ANTIBACTERIAL_ACTIVITY_FROM_GARCINIA_LIVIGSTONEI-MEDIPHERD-https://www.researchgate.net/publication/262460071_Extraction_of_citronella_Cymbopogon_nardus_essential_oil_using_supercritical_CO2_Experimental_data_and_mathematical_modeling"),
("P010", "Serai Kayu", "Salam, Indonesian Bay Leaf", "Myrtaceae", "Syzygium", "polyanthum", "The methanol extract of S. polyanthum leaves and the ethyl acetate extract leaves were potential as acetylcholinesterase inhibitors. The oxidation of linoleic acid was effectively inhibited by S. polyanthum leaf methanolic extract and exhibited no cytotoxic effect against Vero cell line. S. polyanthum ripened fruit displayed significant antioxidant activity (90%) in comparison to ascorbic acid. The three acybenzene derivatives(1-3) and campest-4-en-3-one exhibited a significant protein tyrosine phosphatade 1B inhibitory activity.", "Pheophorbide-α, methyl pheophorbide-α, methyl hydroxypheophorbide-α, pheophorbide-β and hydroxypheophorbide-b (Har LW et al 2012). Gallic acid and caffeic acid (Har LW & Ismail S. 2012).", "https://pubmed.ncbi.nlm.nih.gov/22978223/-MEDIPHERD-https://www.semanticscholar.org/paper/Antioxidant-activity%2C-total-phenolics-and-total-of-LeeWei-Ismail/b1dfee934583b82ca856529d29264c653de465c6-MEDIPHERD-http://rahmaherbalstore.blogspot.com/2011/04/syzygium-polyanthum-for-diabetes.html-MEDIPHERD-https://scialert.net/abstract/?doi=jbs.2013.412.416-MEDIPHERD-http://www.researchgate.net/publication/50867345-MEDIPHERD-https://scialert.net/abstract/?doi=ijp.2012.535.541-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/22763740/"),
("P011", "Serai Acheh", "Tepus wangi, puar kampung", "Zingiberaceae", "Elettariopsis", "smithiae", "Food flavouring as lemon grass substitutes. Afterbirth medicine Calminative for afterbirth Carminative for Flatulence Improve blood circulation To treat yellow fever and bone ache: boil the leaves in water for bathing. To treat wind from the body, facilitate digestion, reduce cholesterol and induce sweating. To in clude into food. Bronchodilating effect and inotropic effect", "", "http://www.tandfonline.com/doi/abs/-MEDIPHERD-http://agrobiosolution.blogspot.com/2010/04/serai-aceh-elettariopsis-smithiae.html"),
("P012", "Sembuluh", "Chinese smartweed, chinese knotweed", "Polygonaceae", "Persicaria", "chinensis", "To treat stomach ache and gastric pain", "Phytochemical analysis revealed that carbohydrate, tannin, alkaloid, steroid, triterpenoid, and flavonoid were present in the extracts of S. polyanthum leaves and ripened and unripe fruits, while saponin was only present in the ripened fruit extract ( Kusuma I.W. et al 2011)", "https://rjppd.org/HTMLPaper.aspx?Journal=Research%20Journal%20of%20Pharmacology%20and%20Pharmacodynamics;PID=2016-8-4-8-MEDIPHERD-https://ijpsr.com/bft-article/evaluation-of-antibacterial-and-antifungal-activities-of-persicaria-chinensis-leaves/-MEDIPHERD-https://gobotany.newenglandwild.org/species/persicaria/chinensis/"),
("P013", "Senduduk Putih", "Senduduk, Senduduk putih, white singapore rhododendron", "Melastomataceae", "Melastoma", "decemfidum", "leaf and root extracts used to treat diarrhea, dysentery, epilepsy and rheumatism. roots with stemwood of Dio som (Laos herb) and soaked with water for drinking and bathing for jaundice remedy. Shoots eaten to treat puerperal infections, high blood pressure and diabetes. Juice used as mouthwash to relieve toothache or treat leucoorhea. bark are used for skin disease treatment. flowers used for cancer treatment and seeds for diarrhea treatment", "", "https://www.academia.edu/14684915/Antioxidant_and_cytotoxic_flavonoids_from_the_flowers_of_Melastoma_malabathricum_L-MEDIPHERD-https://ikm.org.my/ojs/index.php/MJChem/article/download/794/355/-MEDIPHERD-https://www.academia.edu/66268818/Medicinal_plants_An_important_asset_to_health_care_in_a_region_of_Central_Laos-MEDIPHERD-https://www.mdpi.com/1420-3049/26/19/5956/pdf"),
("P014", "Sedap Malam", "Lady of the night, Night blooming Jasmine, Mayang Sari", "Solanaceae", "Cestrum", "nocturnum", "Antidiabetic activity, oral administration of the hydroalcoholic solution leaves extracts in for 15 days caused a significant (P<0.01) reduction in blood glucose levels in diabetic rats.", "Campest-4-en-3-one", "http://www.tandfonline.com/doi/pdf/10.1080/0972060X.2009.10643708-MEDIPHERD-http://www.hindawi.com/journals/aps/2013/150401/"),
("P015", "Sambung Nyawa", "-", "Asteraceae", "Gynura", "procumbens", "Gynura procumbens (Compositae) has been used as folk remedy for the treatment to control diabetes mellitus and hyperlipidemia. Treatment of eruptive fevers, rash, kidney disease, migraine. Constipation, hypertension, diabetes mellitus and cancer (Perry, 1980). G. procumbens is believed by the Chinese to be one that possesses the ability to lower blood pressure and sugar levels. Usually will recommend to eat 3 – 7 leaves daily in the raw form, 5-8 leaves per meal is enough.", "flavonoids, saponins, tannins and terpenoids (Akowuah, et al., 2002). The contents of moisture was 7.08%, carbohydrate was 0.0537 to 0.1968 μg glucose equivalent/100 g dry weight at EGE 0.1 μg mL-1, protein was 4.51 g/100 g dry weight and lipid was 0.023 g/100 g dry weight. As protein source and that have positive effects on free radical scavenging and iron chelating (Puangpronpitag D. et al, 2010)", "https://www.tandfonline.com/doi/abs/10.1076/phbi.40.6.405.8440-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/21150821-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/23874655-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/12602932"),
("P016", "Rumput Cina", "Beijing grass, angel grass", "Commelinaceae", "Murdannia", "bracteata", "Treatment for the kidney and liver, including inflammation and cancer. Trat hapatitis, stomatitis, pneumonia, nephritis", "Hydroxybutenolides such as bracteanolide A and bracteanolide B and isovitexin.", "https://pubmed.ncbi.nlm.nih.gov/17442510-MEDIPHERD-https://www.sciencedirect.com/science/article/pii/S2005290110600362"),
("P017", "Ruku-ruku", "Holy basil, tulasi", "Limiaceae", "Ocimum", "sanctum", "cough, asthma, fever and common cold", "curcuminoids such as cassumunins A, B, C. Phenylbutenoid, Zerumbone.", "https://pubmed.ncbi.nlm.nih.gov/23424203-MEDIPHERD-https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3059441"),
("P018", "Roselle", "Asam paya, asam susur, asam kumbang", "Malvaceae", "Hibiscus", "sabdariffa", "inhibit carbohydrate absorption to a degree and appears to be effective in reducing blood pressure", "The dried calyces contain the flavonoid gossypetin, hibiscetine and sabdaretine. Pigment: hibiscin, daphniphylline, myrtillin, chrysanthenin and delphinidin", "https://scialert.net/fulltext/?doi=ajava.2016.693.700-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/21548802-MEDIPHERD-https://www.ncbi.nlm.nih.gov/pubmed/12926900"),
("P019", "Rosa", "Mawar, China Rose", "Rosaceae", "Rosa", "chinensis", "Treatment of painful menstruation, swollen thyroid, arthritis, boils, poor circulation, stomach pain, swelling etc. , reducing of cancer and the rose oil used in arotheratherapy to aid depression, stress, imsomnia and skin cure", "The flowers rich source of vitamin A, vitamin E, vitamin C, flavenoids and essential fatty acid. The chemical constituents from Rosa chinensis Jacq., which have DPPH· scavenging capacity, dried Rosa chinensis flowers were extracted three times with 95% ethanol under reflux. This extract was then fractionated by column chromatography over silica gel, MCI gel, Sephadex LH-20, etc. A new compound[quercetin 3-O-(2”,6”-digalloyl)-β-D-glucoside, 1] and nine known compounds (2-10) were isolated from Rosa chinensis Jacq. and identified using spectroscopic methods.", "https://link.springer.com/article/10.1007/s00425-021-03778-y-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/16366678"),
("P020", "Ros Jepun", "Rose Moss", "Portulacaceae", "Portulaca", "grandiflora", "To relief sore throat, skin rash and detofication", "P. grandiflora produces the alkaloid type betalain pigment in its petals and stems (Rossi-Hassani BD & Zryd JP 1994). Sterols, carotenoids-in the etheric extract; phenolic acids-in the ethanolic extract; polysaccharides, reducing agents in the aqueous one.", "https://pubmed.ncbi.nlm.nih.gov/15013204-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/7985978"),
("P021", "Pokok Jelai", "Job’s Tear, Coixseed, Tear Grass , Hato Mugi", "Poaceae", "Coix", "lacryma-jobi", "To treat headache, migrain, yellow fever, kidney stone", "-", "https://www.pubs.acs.org/doi/pdf/10.1021/jf00093a010-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/18331775-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/21669575-MEDIPHERD-https://europepmc.org/article/AGR/IND44583360"),
("P022", "Pokok Harum Sundal Malam", "Tuberosa", "Agavaceae", "Polianthes", "tuberosa", "perfume", "The flower volatile compounds were identified as benzyl benzoate, methyl (E)-isoeugenol, ethyl myristate, and methyl anthranilate (Mimaki Y. et al 2002).", "https://pubmed.ncbi.nlm.nih.gov/14738376-MEDIPHERD-https://link.springer.com/chapter/10.1007/978-94-007-7395-0_8"),
("P023", "Patawali", "Akar Seruntum, Akar patawali", "Menispermaceae", "Tinospora", "crispa", "To treat high blood pressure, diabetes, cholera, fever, jaundice, asthma", "Apigenin and magnoflorine", "https://pubmed.ncbi.nlm.nih.gov/21455425-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/22131824-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/22265931"),
("P024", "Nilam", "Patchouli, patchouly, pachouli", "Labiatae", "Pogostemon", "cablin", "Aerial part of Pogostemon cablin has been used against the common cold an as antifungal agent. In Korea, water extract of P. cablin was used for the treatment of fever caused by heart stroke, poor appetite, nausea, apoplexy, etc.", "Patchouli alcohol, pogostone, eugenol, α-bulnesene, rosmarinic acid", "https://www.sciencedirect.com/science/article/pii/S0031942200853121-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/16712790-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/10725128-MEDIPHERD-https://europepmc.org/abstract/MED/2171435"),
("P025", "Nenas Kerang", "Oyster plant, Moses in the cradle", "Cammelinaceae", "Rhoeo", "discolor", "Treatment for cough, cold, nose bleeding, blood in the stool.", "-", "https://pubmed.ncbi.nlm.nih.gov/18063494"),
("P026", "Naga Buana", "Saga buana, pokok kayu putih, semelit", "Euphobiaceae", "Phyllanthus", "pulcher", "Decoction used as an eye wash, nasal ulcers, abscesses, pruritus, fever and renal problems in children", "Bis(6-methyl)phthalate, phyllanthal-A and 3,4-dihydroxy-5-methoxy-3’,4’,4’-trihydroxyoxepino-chromene-2-one stigmast-5-en-3-ol-oleate, disobutyl adipate, β-sitosterol, 7-tridecanone and β-sitosteryl-β-D-glucopyranoside 12(13)-dehydro-3α-acetoxyolean-28-oic acid and lupanol acetate 3 α-acetoxy-25-hydroxyolean-12-en-oic acid, glochidone and glochidonol", "-"),
("P027", "Misai Kuching", "cats whiskers", "Lamiaceae", "Orthosiphon", "stamineus", "To treat kidney stones, nephritis, Gout, High Blood Pressure, Diabetes, rheumatism, anti-allergenic", "Triterpene saponins: (up to 4.5%): aglycone hederagenin. Flavonoids: in particular more highly methoxylized examples (0.2%) including eupatorin, sinensetin, scutella­rine tetramethyl ethers, salvigenin. Volatile oil (0.02-0.06%): including among others β-caryo­phyllene, α-humulene, caryophyllene-epoxide.", "www.sciencedirect.com/science/article/pii/S0944711307000773-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/18600199-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/20937371"),
("P028", "Melada Pahit", "lada pahit, chinese gall brucea, chinese sumac , gallnut, ya tan tze (Chinese)", "Simaroubaceae", "Brucea", "amarissima", "To treat diaria, bloody stool,worms mel, high blood pressure, cholera and gastric", "Seed: Quassinoid glucosides, javanicosides I. J., K. and L. Bruceins D and E. Yadanziosides B,C, E, I and K, bruceoside B and yadanzigan", "https://academicjournals.org/journal/JMPR/article-abstract/6A2786415864"),
("P029", "Mas Cotek", "Mistletoe Fig, Mistletoe Rubber Plant", "Moraceae", "Oicus", "deltoidea", "To help to contract the uterine and vaginal mucles, to regain body strength, improve blood circulation and treating disorder related to menstrual cylce", "", "https://www.phcogres.com/article/2009/1/4/nil-10-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/21278166-MEDIPHERD-https://www.ncbi.nlm.nih.gov/pubmed/18672036-MEDIPHERD-https://www.hindawi.com/journals/ecam/2014/902734"),
("P030", "Markisa", "Passion fruit, Passionfruit, Yellow Maracuya, Yellow Granadilla", "Passifloraceae", "Passiflora", "edulis", "Fruits are processed into juice", "isoorientin, mono-C-deoxyhexosyl flavones. Lucenin-2, vicenin-2, isoorientin, isovitexin, luteolin-6-C-chinovoside and luteolin-6-C-fucoside", "http://informahealthcare.com/doi/pdf/10.1081/CLT-100100919-MEDIPHERD-http://www.globinmed.com/index.php?option=com_content&view=article&id=101982-MEDIPHERD-H.Li, P.Zhou, Q.Yang, Y. Shen, J. Deng, L.Li & D. Zhao (2011). Comparative studies on anxiolytic activites and flavonoid compositions of Passiflora edulis ‘edulis’ and Passiflora edulis ‘flavicarpa’. Journal of Ethnopharmacology 133, 1085-1090. Jun Deng, Y.Zhou, M. Bai & H. Li & L.Li (2010). Anxiolytic and Sedative Activites of Passiflora edulis f. flavicarpa. Journal of Ethnopharmacology Vol 128, Pg 148-153-MEDIPHERD-http://wildlifeofhawaii.com/flowers/937/passiflora-edulis-f-flavicarpa-lilikoi/-MEDIPHERD-S.G. Kulkarni, P. Vijayanand (2010). Effect of ectraction conditions on quality characteristics of pectin from passion fruit peel (Passiflora edulis f. flavicarpa L)-MEDIPHERD-http://en.wikipedia.org/wiki/Passiflora_edulis"),
("P031", "Mahkota dewa", "s crown, Pau, Makuto rojo, Makuto queen and King of drug", "Thymelaceae", "Phaleria", "macrocarpa", "To lower blood sugar levels when it is maked as a tea drink, cure liver disease, hypertension, rheumatism, and also gout. Traditional useful for treating cancer, diabetes, heart disease, hipetensi and weak lust.", "phaleria, gallic acid, Icaricide C, magniferin, mahkoside, dodecanoic acid, palmitic acid, des-acetylflavicordin-A, flavicordin-A, flavicordin-D, flavicordin-A glucoside, ethyl stearate, lignans alkaloids and saponin", "Rabia A. et. al., 2013. Phytochemistry and medicinal properties of Phaleria macrocarpa (Scheff.) Boerl. extracts.Pharmacognosy review. 7 (13):73-80.-MEDIPHERD-Tjandrawinata R. R., Arifin P.F., Tandrasasmita O.M., Rahmi D. and Aripin A. 2010. DLBS1425, a Phaleria macrocarpa (Scheff.) Boerl. extract confers anti proliferative and proapoptosis effects via eicosanoid pathway. Journal Experiment Therapy Oncology. 8(3):187-201.-MEDIPHERD-Hendra R., Ahmad S., Ehsan O., Aspollah S. And M Yunus S. 2011. Antioxidant, anti inflammatory and cytotoxicity of Phaleria macrocarpa (Boerl.) Scheff fruit. BMC Complementary and alternative medicine.11:110.-MEDIPHERD-Saadat P., Maryam J. Y. and Mohammad Aziz D.2013. Effect of Phaleria macrocarpa on sperm Characteristics in adult Rats. Advanced pharmaceutical bulletin.3(2):345-352.-MEDIPHERD-Rabyah B. A., Item J. A., Navneet K., Omar S. A., Mariam a., Roziahanim M. and Mohd Z. A. 2012. Bioassay guided antidiabetic study of Phaleria macrocarpa fruit extracts. Molecules. 17: 4986-5002.-MEDIPHERD-Asturi E., Raharjo TJ, Eviane D. (2007). Cytotoxicity of Phaleria macrocarpa (Scheff) boerl Fruit Flesh and Seed Extract of Ethanol and its Effect Against p53 and Bcl-2 Genes Expression of Normal Cell. International Conference of Chemical Science."),
("P032", "Lilipan", "Redbird flower, slipper plant", "Euphorbiaceae", "Pedilanthus", "tithymaloides", "To treat warts, chloasma, scorpion stings and centipede bites", "Gallic acid, pedilstatin, triterpenes, azafrin, sterol. Kaempferol 3-O-β-D-glucopyranoside-6”-(3-hydroxy-3-methylglutarate, quercitrin & isoquercitrin and scopoletin", "Abreu P., S. Mattgew, T. Gonzalez, D. Costa, M. A. Segundo, E. Fernandes (2006). Anti-inflammatory and antioxidant activity of a medicinal tincture from Pedilanthus tithymaliodes. Life Science Vol 78 (14) Pg 1578-1585.-MEDIPHERD-Mongkolvisut W & S. Sutthivaiyakit (2007). Antimalarial and antituberculous Poly-O-acylated Jatrophane Diterpenoids from Pedilanthus tithymaloides J. Nat Prod , 70 Pg 1434-1438.-MEDIPHERD-Abreu P.M., S. Matthew, T. Gonzalez, L. Vanickova, D. Costa, A. Gomes, M. A. Segundo, E. Fernandes (2008). Isolation and Identification of antioxidants from Pedilanthus tithymaloides. J. Nat Med 62, Pg 62-70."),
("P033", "Limau purut", "Kaffir lime, Jeruk purut, Kabuyau, Ma kruut", "Rutaceae", "Citrus", "hystrix", "It is used as a traditional medicine for stomachache caused by dyspepsia and as a necessary ingredient in most Malay tonic medicines. It is also used to expel worms from children, to relieve headaches and to treat flu. The fruit juice is an expectorant, used to heal swollen gums and can also be used as syampoo.", "-", "http://www.globinmed.com/index.php?option=com_content&view=article&id=62855:citrus-hystrix-dc&catid=367:c-MEDIPHERD-Che Aniha Che Isahak (2008). 99 Herba. pg 58, Alaf 21, Shah Alam.-MEDIPHERD-http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3642446/"),
("P034", "Lidah Ayam", "Bichetii Grass, Siam Lily, False Lily Turf, Wheat Plant", "Liliaceae", "Chlorophytum", "laxum", "to treat diarrhoea and dysentry an also used as demulcent and galactogogue", "-", "http://www.jaycjayc.com/chlorophytum-laxum-bichetii/-MEDIPHERD-http://hortsci.ashspublications.org/content/45/10/1489.full"),
("P035", "Lengkuas geting", "Lengkuas ranting, Lesser Alpina, Lengkuas ranting, lengkuas kecil, lengkuas padang, Cengkenam, Khaa ling", "Zingiberaceae", "Alpinia", "conchigera", "To treat skin disease such as “panau” dan kurap Gungus infection. Liquid from the rhizome to affected area treats infection and rashes, and as a health drink.", "b-sitosterol, stigmasterol and three flavonoids: cardamomin, alpinetin and naringenin5-Meether", "Ahmad NazifAziz a, HalijahIbrahim b, DeviRosmySyamsir b, MasturaMohtar c, Jaya Vejayan d, KhalijahAwang (2013) Antimicrobialcompoundsfrom Alpiniaconchigera Journal of Ethnopharmacology 145 (2013) 798–802.-MEDIPHERD-http://experimentjournal.com/-MEDIPHERD-Pongpiriyadacha Y., P. Nuansrithong, O. Chumbuajan, N. Sirintharawech & D. Chantip (2008). Gastroprotective Effects of the Extract from Alpina conchigera Griff. Rats and The Possible Mechanism. KMITL Sc J., 8 (2).-MEDIPHERD-Saha D. & S. Paul, 2012. Cytotoxic activity of Methanolic Extract of Alpinia conchigera Griff (Family: Zingiberaceae). Asian J. Pharm. Res., 2 (2). Pg 86-88.-MEDIPHERD-Sulaiman MR, Zakaria ZA, Mohamad AS, Ismail M, Hidayat MT, Israf DA, Adilius M. (2010)Antinociceptive and anti-inflammatory effects of the ethanol extract of Alpinia conchigera rhizomes in various animal models.Pharm Biol 48 (8)-MEDIPHERD-http://www.globinmed.com/index.php?option=com_content&view=article&id=79265:alpinia-conchigera-griffith&Itemid=113-MEDIPHERD-http://wannura. wordpress. com/ 2010/02/01/lengkuas-geting-lesser-alpinia-alpinia-conchigera/lengkuas-geting/ (1)"),
("P036", "Lemuju", "Jemuju, mexican mint, Indian borage, cuban oregano", "Lamiaceae", "Plectranthus", "amboinicus", "Treatment of cough, fever, sore throats, mumps and mosquito bite, Malaria fever, hepatopathy and renal", "Alkaloid, carbohydrates, glycosides, proteins,amino acids, flavanoids, quinine, tannins, phenolic compounds and terpenoids. Β-caryophyllene, quercetin, ursolic acids, triterpenic acids, α-pinene, thymol, eugenol, carvacrol, 1-8-cineole, β-phellandrene, p-cyme, salvigenin, crisimaritin and chrysoeriol.", "Brandao E.M., P.H.D.M. Brandao, I.A. Souza, G.S. Paiva, M.de C. Carvalho & C.M. Lacerda (2013). Antineoplastic Effect of Aqueous Extract of Plectranthus amboinicus in Ehrlich Ascites Carcinoma. J. Cancer ,4 (7) Pg 573-576.-MEDIPHERD-http://www.hindawi.com/journals/aps/2013/150401/-MEDIPHERD-Patel R., N.K. Mahobia, R. Gendle, B. Kaushik & S. K. Singh (2010). Diuretic activity of Leaves of Plectranthus amboinicus (Lour) Spreng in male albino rats. Pharmacognosy Res. 2(2), 86-88.-MEDIPHERD-http://en.wikipedia.org/wiki/Plectranthus_amboinicus"),
("P037", "Kunyit", "Tumeric, Indian saffron, Jiang huang", "Zingiberaceae", "Curcuma", "domestica", "It is used internally to treat stomach, liver ailments and externally to heal sores, and as a cosmetic. It is also used as an anti-inflammatory, antimalarial,anthelmintic, bactericide, fungicide, stimulant and for treating sprains, ringworms, neuralgia, rheumatism osteoarthritis and cancer. The dried tumeric rhizome is commonly used as a condiment and to prepare as yellow color dye. A poultice of the rhizomes is applied to the breast for stimulating milk flow.", "curcuminoids, iridoidal glycosides, linalyl 6-O-malonyl-β-D-glucopyranoside, benzyl 6-O-β-Dxylopyranosyl- β-D-glucopyranoside (β-primeveroside), 2- phenylethyl β-primeveroside, 2-phenylethyl 6-O-α-L-rhamnopyranosyl- β-D-glucopyranoside (β-rutinoside), dotriacontanoic acid, dotriacontanol, oleanolic acid, daucosterol, and hesperidin", "Bundy R, et al: Turmeric extract may improve irritable bowel syndrome symptomology in otherwise healthy adults: A pilot study. J Altern Complement Med 10:1015-1018, 2004.-MEDIPHERD-Hanai H, et al: Curcumin maintenance therapy for ulcerative colitis: Randomized, multicenter, double-blind, placebo-controlled trial. Clin Gastroenterol Hepatol 4:1502-1506, 2006-MEDIPHERD-Kuptniratsaikul V, et al: Efficacy and safety of Curcuma domestica extracts in patients with knee osteoarthritis. J Altern Complement Med 15:891-897, 2009.-MEDIPHERD-Ng TP, et al: Curry consumption and cognitive function in the elderly. Am J Epidemiol 164:898-906, 2006-MEDIPHERD-Baum L, et al: Six-month randomized, placebo-controlled, double-blind, pilot clinical trial of curcumin in patients with Alzheimer disease. J Clin Psychopharmacol 28:110-113, 2008-MEDIPHERD-Ravindran J, et al: Curcumin and cancer cells: How many ways can curry kill tumor cells selectively AAPS J 11:495-510, 2009-MEDIPHERD-Dhillon N, et al: Phase II trial of curcumin in patients with advanced pancreatic cancer. Clin Cancer Res 14:4491-4499, 2008. Somasundaram S, et al: Dietary curcumin inhibits chemotherapy-induced apoptosis in models of human breast cancer. Cancer Res 62:3868-3875, 2002.-MEDIPHERD-Bayet-Robert M, et al: Phase I dose escalation trial of docetaxel plus curcumin in patients with advanced and metastatic breast cancer. Cancer Biol Ther 9:8-14, 2010.-MEDIPHERD-Kunnynajjara AB, et al: Curcumin potentiates antitumor activity of gemcitabine in an orthotopic model of pancreatic cancer through suppression of proliferation, angiogenesis, and inhibition of nuclear factor- factor-kappaB-regulated gene products. Cancer Res 67:3853-3861, 2007-MEDIPHERD-Brinker F: Herbal Contraindications and Drug Interactions, 2nd ed. Sandy, OR, Eclectic Medical Publications, 1998.-MEDIPHERD-Pavithra BH, et al: Modification of pharmacokinetics of norfloxacin following oral administration of curcumin in rabbits. J Vet Sci 10:293-297, 2009.-MEDIPHERD-Zhang W, Lim LY: Effects of spice constituents on P-glycoprotein-mediated transport and CYP3A4-mediated metabolism in vitro. Drug Metab Dispos 36:1283-1290, 2008.-MEDIPHERD-Zhang W, et al: Impact of curcumin-induced changes in P-glycoprotein and CYP3A expression on the pharmacokinetics of peroral celiprolol and midazolam in rats. Drug Metab Dispos 35:110-115, 2007"),
("P038", "Lemba", "lumbah, Sweet Seed plant", "Hypocedaceae", "Molineria", "latifolia", "Eating leaves to treat distended stomach. Chewing fruit together with bettel leaves to treat swelling, cut and malaria, kidney disorder, headaches, ulcers and cough. Rhizome soup is used to treat menorrhagia and fever. Flowers and root are used as stomachic and duretic in genito-urinary disorders. Fruits are used for dianbetis control and poultice of the flowers is exerted on inflammations and wounds.", "Curculin", "Kieyot R., S. Yonchai, K. Nakklaing, O. Chaichumporn and Siriphatr Chamutpong (2013). Free Radical Scavenging and Antioxidant Properties of Molineria latifolia Herb. Extracts. Proceeings of the 1st Academic Science and Technology Conference ASTC2013.-MEDIPHERD-http://www.hindawi.com/journals/ecam/2013/601838/-MEDIPHERD-Napisah H., A. Azmahani, A.L. Zubaidi, A. Intan and A. Nazifah (2011). A Preliminary study on the Antimicrobial Properties of Several Plants Collected from Trengganu , Malaysia. J. Agrobiotech , 2,p99-106.-MEDIPHERD-Yamashita H., S. Theerasilp, T. Aiuchi, K. Nakaya, Y. Nakamura & Y. Kurihara (1990). Purification and complete amino acid sequence of a New Type of Sweet Protein with Taste-modifying activity, curculin. The Journal of Biological Chemistry 265 Pg 15770-15775.-MEDIPHERD-http://linaherbs.blogspot.com/feeds/posts/default"),
("P039", "Kesinai", "serinar, Sandpaper tree, siamese rough bush, tooth brush tree, Peleh, serut", "Moraceae", "Streblus", "asper", "Root: as an application to unhealtyh ulcers and sinuses and as antidote to snake bite, in epilepsy and obesity. Stem: Toothache; Stem bark: given in fever, dysentry and diarhea, stomachache, urinary complaints, useful in piles, edema and wounds, decoction effective ahainst lymphadema, chylurea and other effects of filariasis. Leaves: Eye complaints. Milky juice/latex: Antiseptic, astringent, applied to chapped hands and sore feet in pneuminia and swells of cheek. Fruit: Eye complaints Seed: Epistaxis and diarrhea. Part not specified: Cancer, cholera, colic diarrhea dysentery and menorrhagia, epilepsy and inflammatory swellings", "Cardiac glycosides, α-amyrin acetate, lupeol acetate, β-sitosterol, α-amyrin, lupeol and diol, strebloside and mansonin, phytol, α-farnesene, trans-farnesyl acetate, caryophyllene and trans-trans-a-farnesene", "Gaitonde BB, Vaz AX, Patel JR. Chemical and pharmacological study of root bark of Streblus asper Linn. Indian J Med Sci 1964;18:191–9.-MEDIPHERD-Kumar R.B.S. A. Puratchikodi, A. Prasanna, N. Dolai, P. Majumder, U.K. Mazumder and P.K. Haldar (2011). Pre clinical studies of Streblus asper Lour in terms of behavioural safety and toxicity. Orient Pharm Exp Med. Dio 10.1007/s13596-011-0040-4 http://www.researchgate.net/publication/216033395-MEDIPHERD-Phutdhawong W., Donchai A, Korth J., Pyne SG., Picha P., Ngamkham J., Buddhasukh D., (2004). The components and anticaner activity of the volatile oil from Strblus asper. Flav. Frag J ., 19; 445-447.-MEDIPHERD-Singh SN, Raina D, Chatterjee RK, Srivastava AK.(1998). Antifilarial glycosides of Streblus asper: effect on metabolism of adult Setaria cervi females. Helminthologia ;35:173–7.-MEDIPHERD-http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1475940/pdf/nel018.pdf-MEDIPHERD-http://www.globinmed.com/index.php?option=com_content&view=article&id=79114:streblus-asper-lour&catid=383:s"),
("P040", "Kerak Nasi", "Bread Flower", "Apocynaceae", "Vallaris", "glabra", "It is traditionally used for sores and wounds. Barks are chewed for fixing teeth", "terpenoids, tannins and saponins", "Das S.K., Pansuriya P.V., S.T. Shukla, K.J. Gohil, S.P. Roy, A. Choudhury, V.N. Sutariya (2013). Preclinical evaluation of Vallaris solanacea (roth) Kuntze stem for its antiulcer and antioxidant activity in wistar albino rats Orient Pharm Exp Med. DOI 10.1007/s13596-013-0133-3.-MEDIPHERD-Das S.K., Pansuriya P.V., S.T. Shukla, K.J. Gohil, S.P. Roy, A. Choudhury, V.N. Sutariya (2013). Preclinical evaluation of Vallaris solanacea (roth) Kuntze stem for its antiulcer and antioxidant activity in wistar albino rats Orient Pharm Exp Med. DOI 10.1007/s13596-013-0133-3.-MEDIPHERD-Wong S.K., Lim YY., Abdullah NR & Nordin F.J.(2011) Assessment of antiprolifertive and plasmodial activities of five selected Apocynaceae species. BMC Complemetary & Alternative Medicine.,11(3);1-8.-MEDIPHERD-http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3032759/-MEDIPHERD-Wongpornchai, S., Sriseadka, T., Choonvisase, S. (2003). dentification and quantitation of the rice aroma compound, 2-acetyl-1-pyrroline, in bread flowers (Vallaris glabra Ktze)”. Journal of Agricultural and Food Chemistry 51: 457–462. DOI: 10.1021/jf025856x.-MEDIPHERD-Ng, F.S.P. (2006). “Tropical Horticulture and Gardening”. Clearwater Publications, Kuala Lumpur, Malaysia, 361 p., ISBN: 983-42954-0-5.-MEDIPHERD-Vohra, M.M.; Patnaik, G.K.; Kapil, R.S.; Anad,N. (1966).”Chemistry and pharmacology of a glycoside of Vallaris solanacea. Journal of Pharmaceutical Science, Vol 55(12, Pg 1452-1428."),
("P041", "Kemunting Cina", "Cape periwinkle, Rose periwinkle, rosy periwinkle, old maid", "Apocynaceae", "Catharanthus", "Roseus", "Its extracts of roots and shoots have been used against disease such as diabetes, malaria and Hodgkin’s lymphoma. It is used for high blood pressure, made a gargle to ease soar throats and chest ailments and laryngitis extract of the flower administered as an eyewash for the eyes of infants. Its leaves are used for menorrhagia and reumatism. Its stalks and leaves are used for dysmenorrhea.", "vinblastine", "DukeJ.A. 1985. Handbook of Medicinal Herbs.-MEDIPHERD-Duke J. A. 1993. Magic and Medicine of Plants.-MEDIPHERD-Van der Heijden R., jacobs D I., Snoeijer W., Hallard D and Verpoorte R. 2004. The Catharantus alkaloids : Pharmacognosy and biotechnology. Current medicinal chemistry. 11(5):607-628.-MEDIPHERD-BS Nayak and Lexley M. P. P. 2006 . Catharantus roseus flower extract has wound healing activity in Sprague Dawley rats. BMC Complimentery and alternative medicine. 6:41.-MEDIPHERD-Soon H. T., Chung Y. L., Hazrina H., Aditya A., Mohammadjavad P., Won F. W., Shiau C.C., Mohd Rais M. and Khalijah A. 2013. Antidiabetic and antioxidant of alkaloids from Catharanthus roseus (L.)G. Don. Molecules. 18:9770-9784.-MEDIPHERD-Som N. S., Praveen V., Shoba S., Radhey S., M.M.L. Kumria, S. Ranganathan and K.Sridharan. 2001. Effect of an antidiabetic extract of Catharantus roseus on enzymic activities in streptozocin induced diabetic rats. Journal of Ethopharmacology. 76:269-277.-MEDIPHERD-Srinivas N., Murthy K. B., Srinivas D. L. and Ravindra B. S. B. 2003. The juice of fresh leaves of Catharanthus roseus Linn. Reduces blood glucose in normal and alloxan diabetic rabbits. BMC Complementary and Alternative Medicine. 3:4.-MEDIPHERD-Nor Hazwani A., Rohanizah A. R. and Ishak M.Catharanthus roseus aqueous extract is cytotoxic to Jurkat Leukaemic T-cells but induces the proliferation of normal peripheral blood mononuclear cells. Tropical Life Sciences Research. 21(2):101-113."),
("P042", "Jeruju", "Sea Holly", "Acanthaceae", "Acanthus", "Ilicifolius", "The plants ere used to treat cancer, hepatitis, hepatosplenomegaly, lymphadenophathy, asthma, gastric. Leaves , seeds and roots used as vermifuge. Leaves are used to treat rheumatism. Whole plant to treat kidney stone", "", "Babu BH, Sylesh BS, Padikkala J. Antioxidant and hepatoprotective effect of Acanthus ilicifolius. Fitoterapia. 2001;72:272–7.-MEDIPHERD-Babu BH, Sylesh BS, Padikkala J. Tumour reducing and anticarcinogenic activity of Acanthus ilicifolius in mice. J. Ethnopharmacol. 2002;79:27–33.-MEDIPHERD-Bose S, Bose A. Antimicrobial activity of Acanthus ilicifolius. Indian J Pharm Sci. 2008;70:821–3.-MEDIPHERD-Gupta AK, Tandon N, Sharma M. Reviews on Indian medicinal plants Indian Council of Medical Research, New Delhi. 2004:127–31.-MEDIPHERD-Kapil A, Sharma S, Wahidulla S. Leishmanicidal activity of 2-benzoxazolinone from Acanthus ilicifolius in vitro. Planta Med. 1994;60:187–8.-MEDIPHERD-Mani Senthil Kumar KT, Gorain B, Roy DK, Samanta SK, Pal M, Biswas P, et al. Anti-inflammatory activity of Acanthus ilicifolius. J Ethnopharmacol. 2008;120:7–12-MEDIPHERD-Nizamuddin BS, Danamma B, Chitta S, Mohd D, Abdul M. Evaluation of antiulcer activity in the methanol extract of Acanthus ilicifolius leaves in experimental rats. Int J Pharm Ind Res. 2011;1:57–62.-MEDIPHERD-Singh D. & V. Aeri (2013) Phytochemical and pharmacological potential of Acanthus ilicifolius J Pharm Bioallied Sci. 2013 Jan-Mar; 5(1): 17–20.-MEDIPHERD-Thirunavukkarasu P, Ramathan T, Ramkumar L. Hemolytic and antimicrobial effect in the leaves of Acanthus ilicifolius. J Pharmacol Toxicol. 2011;6:196–200.-MEDIPHERD-Van Kiem P, Quang TH, Huong TT, Nhung le LT, Cuong NX, Van Minh C, et al. Chemical constituents of Acanthus ilicifolius L. and effect on osteoblastic MC3T3E1 cells. Arch Pharm Res. 2008;31:823–9.-MEDIPHERD-http://linaherbs.blogspot.com/2011/05/jemuju.html"),
("P043", "Jejarum/siantan", "Jungle geranium, flame of the woods, jungle flame,burning love, red ixora", "Rubiaceae", "Pxora", "coccinea", "In India, the infusions of the leaves and juice from roots are used to treat dysentery, ulcers and gonorrhea", "phytochemicals lupeol, ursolic acid, oleanolic acid, sitosterol, rutin, lecocyanadin, anthocyanins, proanthocyanidins, and glycosides of kaempferol and quercetin", "Lioger, H. A. 1997. Descriptive flora of Puerto Rico and adjacent islands. Vol. 5. Editotial de la Universidad de Puerto Rico, San Juan, PR. 436p.-MEDIPHERD-Kumer, T.K., C.E. Rajini, V.K. Sasidharan, and T. Krishna Kumar. 1997. Antibacterial and antifungal activity of secondary metabolites from some medicinal and other common plant species. Journal of Life Science 2:14-19.-MEDIPHERD-Latha. P.G. and K.R. Panikkar. 2000 . Inhibition of chemical carcinogenesis in mice by Ixora coccinea flowers. Pharmaceutical Biology 38(2): 152-156.-MEDIPHERD-http://www.sbq.org.br/ranteriores/23/resumos/1147.3-MEDIPHERD-Parrotta, J.A. 2001. Healing plants of peninsular India, CAB International, Wallingford, UK and New York. 944p.-MEDIPHERD-Latha. P.G. and K.R. Panikkar. 1999 . Modulatory effects of Ixora coccinea flower on cyclophosphamide-induced toxicity in mice. Phytotherapy Research 13: 517-520.-MEDIPHERD-Latha. P.G. and K.R. Panikkar. 2001 . Chemoprotective effect of Ixora coccinea L. Flowers on cisplatin induced toxicity in mice. Phytotherapy Research 15:364-366."),
("P044", "Kantan", "Torch Ginger, Ginger flower, Red ginger lily, Torch lily, Wild ginger, Combrang, Bunga kantan, Philippine wax flower, Xiang Bao Jiaing, Indonesian Tall Ginger, Boca de Dragon, Rose de Porcelaine, Porcelain Rose.", "Zingiberaceae", "Etlingera", "elatior", "Traditionally used for flavoring the food and for medicinal purposes like reduce diabetes and hypertension. Consumption of inflorescences along with bitter leaves can relieve flatulence in postpartum women. Decoction from the fruit can treate ear ache and the leaves have been used in wound healing.", "caffeoylquinic acids, chlorogenic acid, kaempferol 3-glucuronide, quercetin 3-glucuronide, quercetin 3-glucoside, and quercetin 3-rhamnoside", "Jeevani O.W.M.M., Karim A.A. and Bhat R. 2011 . Evaluation of nutritional quality of torch ginger (Etlingera elatior Jack.) inflorescence. International Food Research Journal. 18(4):1415-1420.-MEDIPHERD-Mai, C.W., Wong, S.Y., Tan, E.L., Balijepalli, M.K and Pichika, M.R. 2009. Antiproliferative and apoptotic studies of the standardised extracts of Etlingera elatior on human colorectal carcinoma cells. Malayisan Journal of Chemistry 11:136-142.-MEDIPHERD-Tan J., Nagaraja H. and Srikumar C. 2011 . Antioxidant effects of Etlingera elatior flower extract against lead acetate – induced perturbations in free radical scavenging enzymes and lipid peroxidation in rats.BMC research notes. 4:69.-MEDIPHERD-E.W.C Chan, Y.Y.Lim and Mohamed Omar. 2006 . Antioxidant and antibacterial activity of leaves of Etlingera species (Zingiberaceae) in Peninsular Malaysia. Food chemistry. 104:1586-1593.-MEDIPHERD-Miean, K.H., & Mohamed, S. (2001). Flavonoid (myricetin, quercetin, kampferol, luteolin and apigenin)content of edible tropical plants. Journal of Agricultural and Food Chemistry. 49 : 3106-3112.-MEDIPHERD-Habsah, M., Amran, M., Mackeen, M.M., Lajis, N.H., Kikuzaki, H., Nakatani, N., et. al. 2000 . Screening of zingiberaceae extracts for antimicrobial and antioxidant activities. Journal of ethnopharmacology. 72:403-410.-MEDIPHERD-Nagaraja H., Tan J., Srikumar C., Mallikarjuna R. And Anupama K. 2010. Protective effect of Etlingera elatior (torch ginger) extract on lead acetate – induced hepatotoxicity in rats. The Journal of Toxicological Sciences. 35(5):663-671.-MEDIPHERD-http://arrow.monash.edu.au/hdl/1959.-MEDIPHERD-Mackeen M.M., Ali A.M., El-Sharkawy S.H., Manap M.Y., Salleh K.M., Lajis N.H. 1997. Antimicrobial and cytotoxic properties of some Malaysian traditional vegetables (ulam). Pharma Biol. 174-8.-MEDIPHERD-Ali A.M., Mackeen M.M., Ei-Sharkawy S.H., Hamid J.A., Ismail N.H., Ahmad F.B.H. 1996. Antiviral and cytotoxic activities of some plants used Malaysian indigenous medicine. Pertanika J Trop Agric Sci.129-36.-MEDIPHERD-Murakami A, Ohigashi H, Koshimizu K. 1994. Possible anti-tumour promoting properties of traditional Thai food items and some of their active constituents. Asia Pac J Clin Nutr. 3:185-91."),
("P045", "Akar Seratus", "Derhaka Mentua, Bujang Hilir, China Lily", "Asparagaceae", "Peliosanthes", "teta", "The roots boil to treat ‘sembelit’, abortion, anti inflammatory, stamina, cough, bronchitis, colic, scabies. Also used as post natal tonic (aphrodisiac) and family planning.", "-", "http://www.theplantlist.org/tpl/record/kew-311498-MEDIPHERD-http://bayulestari.blogspot.com/p/taman-herba.html"),
("P046", "Belimbing Tanah", "White Bat Plant, Janggut Adam", "Dioscoreaceae", "Tacca", "integrifolia", "It has been used for treatment of gastric ulcer, enteritis, hepatitis, controlling blood pressure, improving sexual fuction, treatment of skin abrasion, skin diseases, and various kind of cancers.", "diarylheptanoids, ochratoxin A, amino acids, n-triacontanol, castanogenin, betulinic acid, quercetin-3-a-arabinodise, taccalin, taccalonolides", "https://pubmed.ncbi.nlm.nih.gov/18209708/-MEDIPHERD-https://rdo.psu.ac.th/sjstweb/journal/27-2/06Taccaintegrifolia.pdf-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/20232323/"),
("P047", "Belalai Gajah", "Snake Grass, Sabah Snake Grass, Gendis, She Cao, Phaya plongton", "Acanthaceae", "Clinacanthus", "nutans", "This species has attracted public interest recently due to its high medicinal values for the treatment of cancer, inflammation and various skin problems. The whole plant is used medicinally to regulate menstrual function, reduce swelling, remove blood clots, relieve pain, to set a broken bone, treat injuries from falls, fractures, contusion, strains, anaemia, jaundice, rheumatism, eye diseases. Fresh leaves have long been traditionally used in Thailand as an anti-inflammatory drug to treat insect and snake bite, skin rashes, allergic responses, herpes simple virus (HSV) and varicella-zoster virus (VZV) lesions.", "stigma sterol, lupeol, B-sitosterol, chlorophyll derivatives, sulfur containing glycosides, C-glycosyl flavones, cerebroside and a monoacylmonogalatosylglycerol", "https://pubmed.ncbi.nlm.nih.gov/23533485/-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/8876301/-MEDIPHERD-https://ijpsr.com/bft-article/acute-oral-toxicity-study-of-clinacanthus-nutans-in-mice/-MEDIPHERD-https://www.actahort.org/books/680/680_18.htm"),
("P048", "Ati-ati", "Flame nettle, painted nettle, mayana", "Lamiaceae", "Coleus", "blumei", "Primarily used for pain, sore, swelling and cuts and in other instances as adjunct medication for delayed menstruation and diarrhea.", "alkaloids, saponins, flavonoids, tannin, volatile oil, quercetin", "http://www.tandfonline.com/doi/pdf/10.1080/15226514-MEDIPHERD-https://pubmed.ncbi.nlm.nih.gov/11456107/-MEDIPHERD-https://www.herbanext.com/philippine-medicinal-herbs/mayana"),
("P049", "Alamanda", "Golden trumpet vine, Yellow Bell, Huang ying", "Apocynaceae", "Allamanda", "cathartica", "In Suriname’s traditional medicinec the roots are used against juandice, complication with malarian and enlarged spleen. The flowers act as a laxative and antibiotic against Staphyloccus spp, and malaria. In Guiana, the latex is used as a purgative and employed for colic. In Surinam, the plant is used as a cathartic (http://stuartxchange. com/Kampanilya.html). Leaves used as purgative or emetic in Southeast Asia. Leaves are also used as an antidote, and for relieving coughs and headaches.", "alkaloids, flavonoids, saponins, carbohydrates, allamandin, 7-Methyl-5,9-octadecadienoic acid", "http://informahealthcare.com/doi/abs/10.3109/13880209209054001-MEDIPHERD-http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1456996-MEDIPHERD-http://www.ces.ncsu.edu/depts/hort/consumer/poison/Allamca.htm-MEDIPHERD-http://books.google.com.my/Allamanda-MEDIPHERD-http://www.fs.fed.us/global/iitf/pdf/shrubs/Allamanda%20cathartica.pdf-MEDIPHERD-http://stuartxchange.com/Kampanilya.html-MEDIPHERD-http://informahealthcare.com/doi/abs/10.3109/13880209209054001-MEDIPHERD-http://onlinelibrary.wiley.com/doi/10.1111/j.1439-0272.2008.00866.x/pdf-MEDIPHERD-https://www.ipindexing.com/article/12352"),
("P050", "Bangun Bangun", "Indian mint, Indian Borage, Spanish thyme, Karpuravalli", "Lamiaceae", "Plectranthus", "amboinuicus", "Used to treat malarial fever, hepatopathy, renal and vesical calculi, cough, chronic asthma, hiccough, bronchitis, helminthiasis, colic, convulsions, epilepsy, skin ulcerations, scorpion bite, skin allergy, wounds, diarrhoea, promote liver health, stimulate lactation for the month or so following childbirth.", "2alpha,3alpha,19alpha,23-Tetrahydroxyursolic-Acid, 2alpha,3alpha-Dihydroxyoleanolic-Acid, Alpha-Thujene, Crategolic-Acid, Euscaphic-Acid, Kilocalories, Tomentic-Acid, Ursolic-Acid, Oleanolic-Acid, Ascorbic-Acid, Ash, Beta-Carotene, Calcium, Carbohydrates, Chrysoeriol, Fat, Fiber, Iron, Niacin, Oxalic-Acid,Phosphorus, Pomolic-Acid, Protein, Riboflavin, Thiamin, Carvacrol", "-"),
("P051", "Jarum Tujuh Bilah", "Leaf cactus, rose cactus, wax rose, Cak Sing Cam, Qi Xing Zhen", "Cactaceae", "Pereskia", "bleo", "The leaves either eaten raw, chewed or taken as a concoction brewed and drink as a tea made from the mature leaves (6–7 pieces) is claimed to treat diabetes, hypertension, rheumatism and for revitalizing the body.It also used as remedies for the relief of headache, gastric pain, ulcers, hemorrhoids, atopic dermatitis. There are also claims that the regular consumption of these leaves can be used to prevent and treat cancer.", "Secondary metabolites with versatile phramcological activities. These compounds include flavanoids, phenols,phenolic glycosides, saponins, cyanogenic glycosides, unsaturated lactones and glucosinolates.", "-"),
("P052", "Halia Bara", "Halia udang, halia merah", "Zingiberaceae", "Zingiber", "officinale", "Rhizole for treating stomach discomfort, tumours, relieving rheumatic pains and as post partum medicine", "The leaf oil was clearly dominated by β-caryophyllene (31.7%), while the oil from the rhizomes was predominantly monoterpenoid, with camphene (14.5%), geranial (14.3%), and geranyl acetate (13.7%) the three most abundant constituents.", "http://umrefjournal.um.edu.my/public/article-view.php-MEDIPHERD-https://qmro.qmul.ac.uk/xmlui/handle/123456789/3350-MEDIPHERD-http://www.ukm.my/mjas/v12_n3/html/12_3_18.html-MEDIPHERD-https://www.thieme-connect.com/ejournals/abstract/10.1055/s-0029-1234377"),
("P053", "Capa Merah", "Sembung, Blumea camphor, Ai na xiang", "Compositae", "Blumea", "balsamifera", "To treat internal wound, rheumatism, hypertension, kidney stones, wounds and cuts, anti-diarrhea, anti spasms, colds and coughs and hypertension", "Flavanoids, terpenes, lactones, Blumealactone A,B,C. Volatile oil contitients were borneol (33.22 %), caryophyllene (8.24 %), ledol (7.12%), tetracyclo [6,3,2,0,(2.5).0(1,8) tridecan-9-ol, 4,4-dimethyl (5.18%), phytol(4.63%), caryophyllene oxide(4.07%), guaiol (3.44%), thujopsene-13 (4.42%), dimethoxydurene (3.59%) and γ-eudesmol (3.18%)", "http://www.banglajol.info/bd/index.php/BJB/article/viewArticle/5132-MEDIPHERD-http://www.worldscientific.com/doi/abs/10.1142/S0192415X09007326"),
("P054", "Gaharu", "Agarwood, Eagle's wood, Aloe wood, Agaru", "Thymelaeaceae", "Aquilaria", "agallocha", "To treat inflammation, arthritis, vomiting, cardiac disorders, cough, asthma, leprosy, anorexia, headache and gout.", "Leaf and bark methanol extracts contain alkaloids, anthroquinones, triterpenoids, tannins, fixed oils and fats and glycosides whereas saponins, fixed oils and fats, alkaloids and triterpenoids were found in the aqueous extracts.The oil contained octacosane, naphthalene, caryophyllene oxide, cadinene", "http://www.banglajol.info/bd/index.php/BJP/article/viewArticle/851-MEDIPHERD-http://www.ajol.info/index.php/ajb/article/view/59366-MEDIPHERD-http://www.sciencedirect.com/science/article/-MEDIPHERD-http://eds.b.ebscohost.com/ehost/-MEDIPHERD-http://www.ijbmsp.org/index.php/IJBMSP/article/view/5-MEDIPHERD-http://saspublisher.com/wp-content/uploads/2013/02/SJAMS-119-12.pdf"),
("P055", "Cabai Emas", "Snake Jasmine, Dainty Spurs", "Acanthaceae", "Rhinacanthus", "nasutus", "In Thai folk remedy, the docoction of roots or whole plant is drunk for treatment of cancer. The plant also used for treatment of ringworm and skin deseases.", "Rhinacanthin C, flavonoids, anthraquinones, tritepenes, sterol, naphthoquinones", "http://www.ijrpc.com/files/29-3144.pdf-MEDIPHERD-http://idosi.org/larcji/1(5)10/8.pdf-MEDIPHERD-http://astp.jst.go.jp/modules/-MEDIPHERD-http://www.pharmacy.mahidol.ac.th/mujournal"),
("P056", "Bunga Telang", "Asian pigeonwings, bluebellvine, blue pea, butterfly pea, cordofan pea, Darwin pea", "Fabaceae", "Clitoria", "ternatea", "promote memory and inteligence, cure insect bites, skin diseases, infections of eye, and entire plant is used as antidote for snake bites. The roots are most widely used and are bitter, refrigerant, laxative, intellect promoting, diuretic, antihelmintic and tonic and are useful in dementia, hemicrania, burning sensation, leprosy, inflammation, leucoderma, bronchitis, asthma, pulmonary tuberculosis, ascites and fever. The seeds are cathartic, while the leaves are used in otalgia and hepatopathy.", "Total plant protein ranges from 14-20 %. The petroleum ether (60-80°C) flower extracts reveals the presence of Taraxerol, a pentacyclic triterpenoid. Flowers contain of steroids, triterpenoid, saponins, resins, tannins and starch in petroleum ether (60-80°C).", "-"),
("P057", "Bunga Raya", "Bunga sepatu, kembang sepatu, rose mallow, chinese hibiscus, china rose, shoe flower", "Malvaceae", "Hibiscus", "rosa-sinensis", "Traditionally, the leaves of the plant are believed to cure fatigue and skin diseases. Flowers are used in epilepsy, leprosy, bronchial catarrh and diabetes. Fresh root juices are used to treat gonorrhea and the powdered root for menorrhagia. The root is also traditionally used to treat coughs.", "Leaves and stems: stigmasterol, β-sitosterol, taraxeryl acetate, cyanidin diglucoside, flavonoids, vitamins, thiamine, fiboflavin, niacin, ascorbic acid; Flowers (yellow colour flowers): quercetin-3-diglucoside, 3,7-diglucoside, cyanidin-3,5-diglucoside, cyanidin-3-sophoroside-5-glucoside; Flowers (ovary of white flowers): quercetin-3-diglucoside, 3,7-diglucoside, cyanidin-3,5-diglucoside, cyanidin-3-sophoroside-5-glucoside, kaempferol-3-xylosylglucoside", "http://www.health-from-nature.net/Hibiscus.html-MEDIPHERD-http://en.wikipedia.org/wiki/Hibiscus_rosa-sinensis"),
("P058", "Bismillah", "Bitter leaf, Vernonia Tree, Pokok Afrika", "Acanthaceae", "Vernonia", "amygdalina", "The plant used as tonic, control of cough, feverish condition, constipation and hypertension", "Saponin, sesquiterpene, flavonoids, Steroid glycosides-type vernoiside B1.", "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2464769/-MEDIPHERD-http://eujournal.org/index.php/esj/article/view/1955-MEDIPHERD-http://www.medwelljournals.com/abstract/?doi=rjpharm.2013.7.11-MEDIPHERD-http://www.sjournals.com/index.php/SJBS/article/view/596-MEDIPHERD-http://eds.a.ebscohost.com/ehost/pdfviewer/-MEDIPHERD-http://www.fao.org/livestock/agap/frg/Visit/Ida/Vernonia%20amygdalina.htm"),
("P059", "Bunga Melur", "Jasmine, Bunga Melati", "Oleaceae", "Jasminum", "sambac", "Flowers and leaves are largely used to prevent and treat breast cancer and stopping uterine bleeding. Reduce the shortness of breath and as treatment of acne. Root is used to treat headace and insomnia and is believed can accelerate fracture healing. Essential oil is used as fregrance for skin care products as it tones the skin as well as reduces skin infalmmation.", "Chemical constitutents in root are dotriacontanoic acid, dotriacontanol, oleanolic acid, daucosterol and hesperidin. Linalyl β-d-glucopyranoside and its 6′-O-malonate were isolated as aroma precursors of linalool from flower buds of Jasminum sambac guided by enzymatic hydrolysis followed by GC and GC-MS analyses", "http://www.researchgate.net/publication/43120136-MEDIPHERD-http://www.hindawi.com/journals/ecam/2012/786426/-MEDIPHERD-http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3320082/pdf/ECAM2012-471312.pdf-MEDIPHERD-http://europepmc.org/abstract/MED/15706849-MEDIPHERD-http://www.sciencedirect.com/science/article/pii/0031942294E0200C-MEDIPHERD-http://en.wikipedia.org/wiki/Jasminum_sambac"),
("P060", "Bisa Ular", "Hophead, hop-headed barleria", "Acanthaceae", "Barleria", "lupulina", "To treat poisonous bites, externally used as an antiinflammatory for insect bite, herpes simplex and herpes zoster. Treatment of rheumatoid arthritis, relieve mental tension and disturbance, treatment of diabetes.", "From the aerial part of Barleria lupulina, 8-O-acetyl-6-O-trans-p-coumaroylshanzhiside, saletpangponosides A–C and 8-O-acetylmussaenoside were isolated together with 13 known compound, Iridoid glucosides. The leaf and stem contain alkaloid.", "http://www.globinmed.com/index.php?option=com_content&view=article&id=79313:barleria");

INSERT INTO materials(mat_id, mat_desc) VALUES
("M01", "bark"),
("M02", "barks"),
("M03", "bulb"),
("M04", "flowers"),
("M05", "flower buds"),
("M06", "fruit"),
("M07", "grain"),
("M08", "inflorescences"),
("M09", "latex"),
("M10", "leaves"),
("M11", "oil"),
("M12", "pods"),
("M13", "rhizomes"),
("M14", "rind"),
("M15", "roots"),
("M16", "sap"),
("M17", "seeds"),
("M18", "shoots"),
("M19", "stalks"),
("M20", "stem"),
("M21", "stem bark"),
("M22", "stem latex"),
("M23", "stem tips"),
("M24", "whole"),
("M25", "wood"),
("M26", "young shoots");

INSERT INTO keywords(keyw_id, keyw_desc) VALUES
("K001", "abscesses"),
("K002", "acne"),
("K003", "afterbirth"),
("K004", "allergy"),
("K005", "analgesic"),
("K006", "anthelmintic"),
("K007", "anti-bacterial"),
("K008", "anticholineterase"),
("K009", "anti-fertility"),
("K010", "anti-fungal"),
("K011", "anti-inflammatory"),
("K012", "anti-microbial"),
("K013", "antioxidant"),
("K014", "antipyretic"),
("K015", "antiseptic"),
("K016", "apoplexy"),
("K017", "arthritis"),
("K018", "asthma"),
("K019", "astringent"),
("K020", "bactericide"),
("K021", "bites"),
("K022", "blister"),
("K023", "blood circulation"),
("K024", "blood pressure"),
("K025", "bloody stool"),
("K026", "bone ache"),
("K027", "cancer"),
("K028", "centipede bites"),
("K029", "chest ailments"),
("K030", "chloasma"),
("K031", "cholera"),
("K032", "cholesterol"),
("K033", "chylurea"),
("K034", "cold"),
("K035", "color dye"),
("K036", "common cold"),
("K037", "constipation"),
("K038", "cosmestic"),
("K039", "cough"),
("K040", "cuts"),
("K041", "demulcent"),
("K042", "Detergent"),
("K043", "detoxification"),
("K044", "diabetes"),
("K045", "diarrhea"),
("K046", "digestion"),
("K047", "Diuretic"),
("K048", "dysentery"),
("K049", "dysmenorrhea"),
("K050", "dyspepsia"),
("K051", "earache"),
("K052", "edema"),
("K053", "epilepsy"),
("K054", "epistaxis"),
("K055", "expectorant"),
("K056", "expel worms"),
("K057", "eye"),
("K058", "eyewash"),
("K059", "family planning"),
("K060", "fever"),
("K061", "filariasis"),
("K062", "flatulence"),
("K063", "flavoring"),
("K064", "flu"),
("K065", "fungicide"),
("K066", "galactogogue"),
("K067", "gastric"),
("K068", "genito-urinary disorders"),
("K069", "gonorrhea"),
("K070", "gout"),
("K071", "headache"),
("K072", "health drink"),
("K073", "heart disease"),
("K074", "hepatitis"),
("K075", "hepatopathy"),
("K076", "Hepatoprotective"),
("K077", "hepatosplenomegaly"),
("K078", "high blood pressure"),
("K079", "hyperlipidemia"),
("K080", "hypertension"),
("K081", "immunostimulant"),
("K082", "jaundice"),
("K083", "juice"),
("K084", "kidney"),
("K085", "kurap"),
("K086", "leucoorhea"),
("K087", "liver disease"),
("K088", "lymphadenophathy"),
("K089", "malaria"),
("K090", "memory"),
("K091", "menorrhagia"),
("K092", "menstrual"),
("K093", "migrain"),
("K094", "mosquito bite"),
("K095", "mumps"),
("K096", "nephritis"),
("K097", "neuralgia"),
("K098", "nose bleeding"),
("K099", "obesity"),
("K100", "pain"),
("K101", "panau"),
("K102", "perfume"),
("K103", "pneumonia"),
("K104", "puerperal infections"),
("K105", "rashes"),
("K106", "renal"),
("K107", "repellant"),
("K108", "rheumatism"),
("K109", "ringworms"),
("K110", "scorpion stings"),
("K111", "sinuses"),
("K112", "skin"),
("K113", "snake bite"),
("K114", "sore throat"),
("K115", "sores"),
("K116", "stimulate breast milk"),
("K117", "stomach"),
("K118", "stomachache"),
("K119", "sweat inducer"),
("K120", "swelling"),
("K121", "swollen gums"),
("K122", "swollen thyroid"),
("K123", "syampoo"),
("K124", "teeth"),
("K125", "toothache"),
("K126", "tumours"),
("K127", "ulcers"),
("K128", "urinary"),
("K129", "vermifuge"),
("K130", "warts"),
("K131", "wounds"),
("K132", "yellow fever");

INSERT INTO materials_relation(plant_id, mat_id) VALUES
("P013","M01"),
("P040","M02"),
("P005","M03"),
("P013","M04"),
("P018","M04"),
("P019","M04"),
("P020","M04"),
("P022","M04"),
("P027","M04"),
("P038","M04"),
("P049","M04"),
("P056","M04"),
("P059","M04"),
("P059","M05"),
("P002","M06"),
("P010","M06"),
("P028","M06"),
("P030","M06"),
("P033","M06"),
("P039","M06"),
("P044","M06"),
("P021","M07"),
("P044","M08"),
("P039","M09"),
("P049","M09"),
("P005","M10"),
("P006","M10"),
("P007","M10"),
("P009","M10"),
("P010","M10"),
("P011","M10"),
("P013","M10"),
("P014","M10"),
("P015","M10"),
("P016","M10"),
("P017","M10"),
("P024","M10"),
("P025","M10"),
("P026","M10"),
("P027","M10"),
("P029","M10"),
("P033","M10"),
("P038","M10"),
("P039","M10"),
("P041","M10"),
("P043","M10"),
("P044","M10"),
("P047","M10"),
("P048","M10"),
("P049","M10"),
("P050","M10"),
("P051","M10"),
("P053","M10"),
("P058","M10"),
("P060","M10"),
("P054","M11"),
("P056","M12"),
("P003","M13"),
("P004","M13"),
("P008","M13"),
("P011","M13"),
("P035","M13"),
("P037","M13"),
("P038","M13"),
("P046","M13"),
("P052","M13"),
("P033","M14"),
("P001","M15"),
("P003","M15"),
("P011","M15"),
("P013","M15"),
("P026","M15"),
("P034","M15"),
("P039","M15"),
("P041","M15"),
("P042","M15"),
("P043","M15"),
("P045","M15"),
("P049","M15"),
("P053","M15"),
("P055","M15"),
("P026","M16"),
("P013","M17"),
("P042","M17"),
("P013","M18"),
("P041","M18"),
("P041","M19"),
("P023","M20"),
("P039","M20"),
("P039","M21"),
("P032","M22"),
("P027","M23"),
("P031","M24"),
("P033","M24"),
("P036","M24"),
("P037","M24"),
("P042","M24"),
("P051","M24"),
("P055","M24"),
("P057","M24"),
("P054","M25"),
("P003","M26");

INSERT INTO keywords_relation(plant_id, keyw_id) VALUES
("P026","K001"),
("P059","K002"),
("P011","K003"),
("P050","K004"),
("P004","K005"),
("P037","K006"),
("P001","K007"),
("P003","K007"),
("P004","K007"),
("P005","K007"),
("P008","K008"),
("P010","K008"),
("P008","K009"),
("P004","K010"),
("P007","K010"),
("P009","K010"),
("P004","K011"),
("P005","K011"),
("P008","K011"),
("P016","K011"),
("P037","K011"),
("P038","K011"),
("P039","K011"),
("P045","K011"),
("P047","K011"),
("P054","K011"),
("P006","K012"),
("P008","K012"),
("P001","K013"),
("P004","K013"),
("P008","K013"),
("P010","K013"),
("P008","K014"),
("P039","K015"),
("P024","K016"),
("P019","K017"),
("P054","K017"),
("P060","K017"),
("P017","K018"),
("P042","K018"),
("P054","K018"),
("P039","K019"),
("P037","K020"),
("P056","K021"),
("P060","K021"),
("P008","K022"),
("P011","K023"),
("P018","K024"),
("P046","K024"),
("P025","K025"),
("P028","K025"),
("P011","K026"),
("P001","K027"),
("P005","K027"),
("P006","K027"),
("P013","K027"),
("P016","K027"),
("P031","K027"),
("P037","K027"),
("P039","K027"),
("P042","K027"),
("P046","K027"),
("P047","K027"),
("P051","K027"),
("P055","K027"),
("P059","K027"),
("P032","K028"),
("P041","K029"),
("P032","K030"),
("P023","K031"),
("P039","K031"),
("P004","K032"),
("P011","K032"),
("P039","K033"),
("P025","K034"),
("P037","K035"),
("P024","K036"),
("P058","K037"),
("P037","K038"),
("P017","K039"),
("P036","K039"),
("P038","K039"),
("P045","K039"),
("P049","K039"),
("P057","K039"),
("P058","K039"),
("P007","K040"),
("P038","K040"),
("P034","K041"),
("P002","K042"),
("P020","K043"),
("P013","K044"),
("P014","K044"),
("P015","K044"),
("P031","K044"),
("P038","K044"),
("P041","K044"),
("P044","K044"),
("P051","K044"),
("P057","K044"),
("P013","K045"),
("P028","K045"),
("P034","K045"),
("P011","K046"),
("P004","K047"),
("P007","K047"),
("P008","K047"),
("P013","K048"),
("P034","K048"),
("P039","K048"),
("P043","K048"),
("P041","K049"),
("P033","K050"),
("P044","K051"),
("P039","K052"),
("P013","K053"),
("P039","K053"),
("P039","K053"),
("P039","K054"),
("P033","K055"),
("P033","K056"),
("P039","K057"),
("P026","K058"),
("P041","K058"),
("P045","K059"),
("P008","K060"),
("P015","K060"),
("P017","K060"),
("P023","K060"),
("P024","K060"),
("P036","K060"),
("P038","K060"),
("P039","K060"),
("P050","K060"),
("P039","K061"),
("P044","K062"),
("P044","K063"),
("P033","K064"),
("P037","K065"),
("P034","K066"),
("P042","K067"),
("P043","K069"),
("P027","K070"),
("P031","K070"),
("P021","K071"),
("P033","K071"),
("P038","K071"),
("P059","K071"),
("P035","K072"),
("P031","K073"),
("P042","K074"),
("P036","K075"),
("P003","K076"),
("P004","K076"),
("P007","K076"),
("P042","K077"),
("P013","K078"),
("P041","K078"),
("P015","K079"),
("P031","K080"),
("P031","K080"),
("P044","K080"),
("P051","K080"),
("P053","K080"),
("P058","K080"),
("P004","K081"),
("P013","K082"),
("P023","K082"),
("P049","K082"),
("P030","K083"),
("P027","K084"),
("P038","K084"),
("P042","K084"),
("P053","K084"),
("P035","K085"),
("P013","K086"),
("P031","K087"),
("P042","K088"),
("P001","K089"),
("P009","K089"),
("P036","K089"),
("P037","K089"),
("P038","K089"),
("P041","K089"),
("P049","K089"),
("P056","K090"),
("P038","K091"),
("P039","K091"),
("P041","K091"),
("P019","K092"),
("P029","K092"),
("P048","K092"),
("P021","K093"),
("P036","K094"),
("P036","K095"),
("P027","K096"),
("P037","K097"),
("P025","K098"),
("P039","K099"),
("P012","K100"),
("P048","K100"),
("P035","K101"),
("P022","K102"),
("P016","K103"),
("P013","K104"),
("P020","K105"),
("P035","K105"),
("P036","K106"),
("P009","K107"),
("P013","K108"),
("P031","K108"),
("P037","K108"),
("P041","K108"),
("P042","K108"),
("P052","K108"),
("P053","K108"),
("P060","K108"),
("P037","K109"),
("P032","K110"),
("P039","K111"),
("P013","K112"),
("P047","K112"),
("P055","K112"),
("P056","K112"),
("P057","K112"),
("P008","K113"),
("P020","K114"),
("P036","K114"),
("P041","K114"),
("P040","K115"),
("P037","K116"),
("P038","K117"),
("P052","K117"),
("P012","K118"),
("P033","K118"),
("P039","K118"),
("P011","K119"),
("P038","K120"),
("P048","K120"),
("P033","K121"),
("P019","K122"),
("P033","K123"),
("P040","K124"),
("P013","K125"),
("P039","K125"),
("P052","K126"),
("P026","K127"),
("P038","K127"),
("P039","K127"),
("P043","K127"),
("P050","K127"),
("P039","K128"),
("P042","K129"),
("P032","K130"),
("P039","K131"),
("P040","K131"),
("P044","K131"),
("P011","K132"),
("P021","K132");

